In [27]:
# DATA INSPECTION PHASE

In [1]:
# Upload the CSV into Colab
from google.colab import files

uploaded = files.upload()

Saving healthcare-dataset-stroke-data.csv to healthcare-dataset-stroke-data (1).csv

In [3]:
# Import Libraries
import pandas as pd
import numpy as np
# Load the dataset
df = pd.read_csv("healthcare-dataset-stroke-data.csv")

In [4]:
# Explore the data set
# 1.View First 5 Rows of the data set
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [5]:
# 2. View the size of the data set
df.shape
# This means that the dataframe has 5110 rows and12 columns

(5110, 12)

In [6]:
# 3. View Column Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

In [7]:
# 4 Checking for missing values
df.isnull().sum()

# BMI has 201 missing values.
# All other columns have no missing values.

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [8]:
# 5 View statistics summary of the data set
df.describe()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,5110.000000,5110.000000,5110.000000,5110.000000,5110.000000,4909.000000,5110.000000
mean,36517.829354,43.226614,0.097456,0.054012,106.147677,28.893237,0.048728
std,21161.721625,22.612647,0.296607,0.226063,45.283560,7.854067,0.215320
min,67.000000,0.080000,0.000000,0.000000,55.120000,10.300000,0.000000
25%,17741.250000,25.000000,0.000000,0.000000,77.245000,23.500000,0.000000
50%,36932.000000,45.000000,0.000000,0.000000,91.885000,28.100000,0.000000
75%,54682.000000,61.000000,0.000000,0.000000,114.090000,33.100000,0.000000
max,72940.000000,82.000000,1.000000,1.000000,271.740000,97.600000,1.000000

In [9]:
# 6 View column names of the data set
df.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [10]:
# 7 Check for records duplicate in the data set
df.duplicated().sum()
# This means there are no duplicates in the data set

np.int64(0)

In [ ]:
# INTERPRETATION OF THE DATA INSPECTION PHASE

### 1.  Dataset Overview

# The Stroke Prediction Dataset contains information on:
# 5,110 patients and 12 variables related to demographic characteristics, lifestyle factors, and clinical health indicators.

# The objective of this project:
# is to analyze factors associated with stroke occurrence # develop predictive models that can support early risk identification and preventive healthcare interventions.

 ### 2. Dataset Dimensions

# The dataset contains:

# - 5,110 patient records (rows)
# - 12 variables (columns)
# Each row represents a unique patient and includes demographic, lifestyle, and medical information relevant to stroke risk assessment.


### 3.  Data Type Assessment

# The dataset contains a mix of numerical and categorical variables.

### Numerical Variables
# - id
# - age
# - hypertension
# - heart_disease
# - avg_glucose_level
# - bmi
# - stroke

### Categorical Variables
# - gender
# - ever_married
# - work_type
# - Residence_type
# - smoking_status

# These variable types are appropriate for exploratory analysis and predictive modelling.


## 4.  Missing Value Assessment

# The dataset contains missing values in only one variable:

# | Column | Missing Values |
# |----------|----------|
# | bmi | 201 |

# This represents approximately 3.93% of all records.

# No missing values were found in any other column.

# Because BMI is an important clinical indicator for stroke risk analysis, the missing values will be addressed during the data cleaning process.
# Given the possibility of outliers in BMI measurements, median imputation will be considered.


### Duplicate Record Assessment

# No duplicate records were identified in the dataset.

# This indicates that each patient record appears to be unique and no duplicate removal is required.



## Initial Statistical Insights

### Age

# Patient ages range from 0.08 years to 82 years, indicating the dataset includes both infants and older adults.

### BMI

# BMI values range from 10.3 to 97.6, suggesting the presence of potentially extreme values that should be investigated further during exploratory analysis.

### Average Glucose Level

# Average glucose levels range from 55.12 to 271.74, indicating substantial variation in blood glucose measurements across patients.

### Stroke Occurrence

# Approximately 4.87% of patients experienced a stroke.

# This indicates a highly imbalanced target variable, which will require special attention during predictive modelling to prevent biased model performance.


### Data Quality Summary

# Key findings from the initial data assessment:

# - Dataset contains 5,110 records and 12 variables.
# - No duplicate records were identified.
# - Only the BMI variable contains missing values (201 records).
# - All other variables are complete.
# - The target variable (stroke) is highly imbalanced, with only approximately 4.87% positive stroke cases.
# - Additional cleaning will focus on handling missing BMI values before proceeding to exploratory data analysis.

In [ ]:
# DATA CLEANING PHASE
### Step 1: Calculate the Median BMI

# - Calculate the median (middle value) of the BMI column
# - We do this before filling missing values because we need a replacement value.
# - The median is preferred over the mean because BMI data may contain extreme values (outliers) that could distort the average.

### NOTE
# In medical datasets like stroke prediction:

# - Some patients may have very high BMI (obesity cases)
# - Some may have very low BMI (malnutrition or illness cases)
# - These extreme values are medically valid but can skew averages

# So using the mean: may "inflate" or "deflate" the typical BMI of patients.

# But using the  median: gives more realistic “central patient”

In [11]:
bmi_median = df["bmi"].median()
print("Median BMI: " , bmi_median)

Median BMI:  28.1

In [12]:
## Step 2: Fill missing bmi values
# - Replace all missing BMI values (NaN) with the median BMI value(28.1)
# - This ensures every patient record has a BMI value.
# - We assign the result back to the BMI column so the changes are saved.
df["bmi"] = df["bmi"].fillna(bmi_median)

In [13]:
## Step 3: Verify missing values has been removed
# - Count missing values again after filling BMI.
# - This confirms that the cleaning step worked correctly.
df.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [ ]:
## BMI Missing Value Treatment

# The BMI variable contained 201 missing values, representing approximately 3.93% of the dataset.

# Rather than removing these patient records, median imputation was used to preserve the dataset size and minimize information loss.

# The median was selected because BMI distributions can contain extreme values (outliers), making it a more robust measure of central tendency than the mean.

# After imputation, all missing values were successfully removed, resulting in a complete dataset for subsequent exploratory data analysis and predictive modelling.

In [18]:

###  Step 4: Validate Categorical Variables


# Before performing analysis or machine learning,
# we need to verify that all categorical columns
# contain only expected values.

# This helps  identify:
# - Data entry errors
# - Spelling mistakes
# - Unexpected categories
# - Inconsistent labels

# For example:
# "Male" and "male" would be treated as different categories.
# "Private" and "Privte" would be treated as different categories.

# Therefore, we inspect all unique values
# present in each categorical column.

In [19]:
# Check unique values in Gender column
print("Gender Categories:")
print(df["gender"].unique())

# Reason:
# Gender is a categorical variable.
# We want to verify that only valid categories exist
# such as Male, Female, and Other.

Gender Categories:
['Male' 'Female' 'Other']

In [20]:
# Check unique values in Ever Married column
print("\nEver Married Categories:")
print(df["ever_married"].unique())

# Reason:
# We expect only two categories:
# Yes and No.
# Any additional value may indicate a data quality issue.

Ever Married Categories:
['Yes' 'No']

In [21]:
# Check unique values in Work Type column
print("\nWork Type Categories:")
print(df["work_type"].unique())

# Reason:
# We want to identify all employment categories
# represented in the dataset and ensure no spelling errors exist.

Work Type Categories:
['Private' 'Self-employed' 'Govt_job' 'children' 'Never_worked']

In [22]:
# Check unique values in Residence Type column
print("\nResidence Type Categories:")
print(df["Residence_type"].unique())

# Reason:
# We expect only Urban and Rural.
# Any additional category should be investigated.

Residence Type Categories:
['Urban' 'Rural']

In [23]:
# Check unique values in Smoking Status column
print("\nSmoking Status Categories:")
print(df["smoking_status"].unique())

# Reason:
# Smoking status is an important stroke risk factor.
# We need to verify all valid categories.

# Note:
# "Unknown" is a valid category according to
# the dataset documentation and should NOT be removed.

Smoking Status Categories:
['formerly smoked' 'never smoked' 'smokes' 'Unknown']

In [ ]:
# CATEGORICAL VARIABLE VALIDATION

# All categorical variables were reviewed to identify
# unexpected values, spelling inconsistencies,
# and potential data quality issues.

# Variables validated:
# - gender
# - ever_married
# - work_type
# - Residence_type
# - smoking_status

# No unexpected categories were identified.

# The category "Unknown" in smoking_status
# is considered valid and represents patients
# whose smoking history information is unavailable.

# Therefore, it will be retained for analysis.

In [24]:

### Step 5: Validate Stroke Target Variable


# The stroke column is the target variable
# for this project.

# According to the dataset documentation:
# 0 = No Stroke
# 1 = Stroke

# We need to verify that only these two values exist.

# Reason:
# Machine learning models require clean target labels.

# If unexpected values such as:
# 2, Yes, No, Missing, etc.
# exist in the target column,
# they could cause modelling errors.

# Therefore, we validate the target variable
# before proceeding further.

print("Stroke Categories:")
print(df["stroke"].unique())

Stroke Categories:
[1 0]

In [ ]:
# TARGET VARIABLE VALIDATION

# The stroke variable was successfully validated.

# Valid values observed:
# - 0 = No Stroke
# - 1 = Stroke

# No unexpected target values were found.

# The dataset is therefore suitable
# for binary classification modelling.

In [25]:
### Step 6: Assess Stroke Class Balance
# Count the number of observations
# in each stroke category.

stroke_counts = df["stroke"].value_counts()

print(stroke_counts)

stroke
0    4861
1     249
Name: count, dtype: int64

In [26]:
# Calculate percentage distribution
# of each stroke category.

# Reason:
# Healthcare datasets frequently contain
# imbalanced target variables.

# In this dataset,
# stroke cases are expected to be much less frequent
# than non-stroke cases.

# Understanding class balance helps us decide
# whether special techniques such as SMOTE
# will be required during model development.

# Class imbalance can cause a model
# to become biased toward predicting
# the majority class.

stroke_percentages = (
    df["stroke"]
    .value_counts(normalize=True)
    * 100
)

print(stroke_percentages)

stroke
0    95.127202
1     4.872798
Name: proportion, dtype: float64

In [ ]:
# STROKE CLASS DISTRIBUTION

# The target variable is highly imbalanced.

# The majority of patients did not experience a stroke,
# while only a small percentage experienced a stroke event.

# This is common in healthcare datasets
# because severe medical outcomes occur less frequently
# than normal outcomes.

# To improve predictive performance,
# class balancing techniques such as SMOTE
# may be considered during feature engineering.

In [27]:

### STEP 7: Remove ID Column


# The id column is a unique patient identifier.

# It does not contain any clinical,
# demographic, or behavioural information.

# Therefore, it provides no predictive value
# for stroke risk analysis.

# Keeping identifier columns may introduce noise
# into machine learning models.

# For this reason, the id column is removed.

df = df.drop(columns=["id"])

In [28]:
# Verify that the id column has been removed.

df.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [29]:
# IDENTIFIER COLUMN REMOVAL

# The id column was removed from the dataset.

# This column served only as a unique record identifier
# and contained no useful information
# for healthcare analytics or stroke prediction.

# Removing irrelevant variables helps improve
# model efficiency and analytical clarity.

Interpretation of Categorical Variable Validation
## Categorical Variable Validation

All categorical variables were reviewed to identify unexpected values, spelling inconsistencies, and potential data quality issues.

### Gender

Valid categories identified:

* Male
* Female
* Other

### Ever Married

Valid categories identified:

* Yes
* No

### Work Type

Valid categories identified:

* Private
* Self-employed
* Govt_job
* children
* Never_worked

### Residence Type

Valid categories identified:

* Urban
* Rural

### Smoking Status

Valid categories identified:

* formerly smoked
* never smoked
* smokes
* Unknown

No unexpected categories, spelling errors, or data entry inconsistencies were identified.

The category **"Unknown"** in the smoking_status variable is considered a valid value according to the dataset documentation and represents patients whose smoking history information is unavailable. Therefore, it was retained for analysis.

Interpretation of Stroke Target Validation
## Target Variable Validation

The stroke variable was validated to confirm that it contains only binary outcome values.

Observed values:

* 0 = No Stroke
* 1 = Stroke

No unexpected values were found.

This confirms that the target variable is suitable for binary classification modelling.

Interpretation of Class Balance Assessment
## Stroke Class Distribution

The distribution of the target variable is shown below:

| Stroke Status | Count | Percentage |
| ------------- | ----- | ---------- |
| No Stroke (0) | 4,861 | 95.13%     |
| Stroke (1)    | 249   | 4.87%      |

The dataset is highly imbalanced, with the majority of patients not experiencing a stroke.

This imbalance is common in healthcare datasets because serious medical events occur less frequently than normal outcomes.

If not addressed, machine learning models may become biased toward predicting the majority class (No Stroke) while failing to identify stroke cases effectively.

To improve predictive performance, class balancing techniques such as SMOTE (Synthetic Minority Over-sampling Technique) will be considered during the feature engineering phase.

Interpretation of ID Column Removal

Index(['gender', 'age', 'hypertension', 'heart_disease',
       'ever_married', 'work_type', 'Residence_type',
       'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

## Identifier Column Removal

The id column was removed from the dataset.

This variable served only as a unique patient identifier and did not contain any clinical, demographic, or behavioural information relevant to stroke prediction.

Removing non-informative variables helps improve analytical clarity and prevents machine learning models from learning patterns that have no predictive significance.

In [30]:
# Save the final cleaned dataset for use in EDA and modelling

df.to_csv(
    "/content/drive/MyDrive/PERSONAL PROJECTS/MENTORSHIP PROJECTS/1 Stroke Risk Prediction & Clinical Insights Analysis/stroke_cleaned.csv",
    index=False
)

In [31]:
df.to_csv("stroke_cleaned.csv", index=False)